# ZSH

[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-dircolors-solarized"]
    type = "archive"
    url = "https://github.com/joel-porquet/zsh-dircolors-solarized/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-dircolors-solarized/dircolors-solarized"]
    type = "archive"
    url = "https://github.com/seebi/dircolors-solarized/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

# Java

[".jenv"]
    type = "archive"
    url = "https://github.com/jenv/jenv/archive/master.tar.gz"
    exact = false
    stripComponents = 1
    refreshPeriod = "2160h" # 90 Day
