{{- $email := "" -}}
{{- if (hasKey . "email") -}}
    {{- $email = .email -}}
{{- else -}}
    {{- $email = promptString "primary email" -}}
{{- end -}}

{{- $hasJavaLang := false -}}
{{- if (hasKey .lang "java") -}}
    {{- $hasJavaLang = .lang.java -}}
{{- else -}}
    {{- $hasJavaLang = promptBool "Install java" -}}
{{- end -}}

[data]
    email = "{{ $email }}"

    [data.lang]
        java = {{ $hasJavaLang }}

[edit]
    command = "code"
    args = ["--wait"]
